# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'frontend/CustomerDashboard.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_CustomerDashboardWindow(object):
    def setupUi(self, CustomerDashboardWindow):
        CustomerDashboardWindow.setObjectName("CustomerDashboardWindow")
        CustomerDashboardWindow.resize(1043, 630)
        CustomerDashboardWindow.setStyleSheet("background-color:rgb(255, 255, 255);\n"
"border-radius:15px;\n"
"\n"
"\n"
"")
        self.centralwidget = QtWidgets.QWidget(CustomerDashboardWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.sidepanel = QtWidgets.QLabel(self.centralwidget)
        self.sidepanel.setGeometry(QtCore.QRect(0, 0, 311, 681))
        self.sidepanel.setStyleSheet("background-color:rgb(161, 198, 185);\n"
"color:rgb(255,255,255);\n"
"padding-left:10px;\n"
"padding-bottom:10px")
        self.sidepanel.setText("")
        self.sidepanel.setObjectName("sidepanel")
        self.user = QtWidgets.QLabel(self.centralwidget)
        self.user.setGeometry(QtCore.QRect(20, 170, 51, 51))
        self.user.setStyleSheet("background-color:rgb(161, 198, 185);")
        self.user.setText("")
        self.user.setPixmap(QtGui.QPixmap("frontend\\images/NFT User_45px.png"))
        self.user.setObjectName("user")
        self.time = QtWidgets.QLabel(self.centralwidget)
        self.time.setGeometry(QtCore.QRect(20, 320, 41, 41))
        self.time.setStyleSheet("background-color:rgb(161, 198, 185);")
        self.time.setText("")
        self.time.setPixmap(QtGui.QPixmap("frontend\\images/time_machine_45px.png"))
        self.time.setObjectName("time")
        self.notification = QtWidgets.QLabel(self.centralwidget)
        self.notification.setGeometry(QtCore.QRect(20, 250, 41, 41))
        self.notification.setStyleSheet("background-color:rgb(161, 198, 185);")
        self.notification.setText("")
        self.notification.setPixmap(QtGui.QPixmap("frontend\\images/Notification_45px.png"))
        self.notification.setObjectName("notification")
        self.image = QtWidgets.QLabel(self.centralwidget)
        self.image.setGeometry(QtCore.QRect(340, -40, 631, 471))
        self.image.setStyleSheet("background-colour:rgb(255,255,255);\n"
"border-colour:rgb(255,255,255);\n"
"")
        self.image.setText("")
        self.image.setPixmap(QtGui.QPixmap("frontend\\images/patient_homepg (1).png"))
        self.image.setObjectName("image")
        self.profile = QtWidgets.QPushButton(self.centralwidget)
        self.profile.setGeometry(QtCore.QRect(70, 180, 161, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.profile.setFont(font)
        self.profile.setStyleSheet("background-color:rgb(161, 198, 185);\n"
"border-radius:10px;\n"
"padding-left:10px;\n"
"padding-bottom:10px")
        self.profile.setObjectName("profile")
        self.history = QtWidgets.QPushButton(self.centralwidget)
        self.history.setGeometry(QtCore.QRect(70, 320, 91, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.history.setFont(font)
        self.history.setStyleSheet("background-color:rgb(161, 198, 185);\n"
"border-radius:10px;\n"
"padding-left:10px;\n"
"padding-bottom:10px")
        self.history.setObjectName("history")
        self.consultation = QtWidgets.QPushButton(self.centralwidget)
        self.consultation.setGeometry(QtCore.QRect(60, 260, 161, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.consultation.setFont(font)
        self.consultation.setStyleSheet("background-color:rgb(161, 198, 185);\n"
"border-radius:10px;\n"
"padding-left:10px;\n"
"padding-bottom:10px")
        self.consultation.setObjectName("consultation")
        CustomerDashboardWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(CustomerDashboardWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1043, 26))
        self.menubar.setObjectName("menubar")
        CustomerDashboardWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(CustomerDashboardWindow)
        self.statusbar.setObjectName("statusbar")
        CustomerDashboardWindow.setStatusBar(self.statusbar)

        self.retranslateUi(CustomerDashboardWindow)
        QtCore.QMetaObject.connectSlotsByName(CustomerDashboardWindow)

    def retranslateUi(self, CustomerDashboardWindow):
        _translate = QtCore.QCoreApplication.translate
        CustomerDashboardWindow.setWindowTitle(_translate("CustomerDashboardWindow", "MainWindow"))
        self.profile.setText(_translate("CustomerDashboardWindow", "Profile Details"))
        self.history.setText(_translate("CustomerDashboardWindow", "History"))
        self.consultation.setText(_translate("CustomerDashboardWindow", "Consultations"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    CustomerDashboardWindow = QtWidgets.QMainWindow()
    ui = Ui_CustomerDashboardWindow()
    ui.setupUi(CustomerDashboardWindow)
    CustomerDashboardWindow.show()
    sys.exit(app.exec_())
