# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'frontend/doctorProfile.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DoctorProfile(object):
    def setupUi(self, DoctorProfile):
        DoctorProfile.setObjectName("DoctorProfile")
        DoctorProfile.resize(573, 607)
        DoctorProfile.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.education = QtWidgets.QLineEdit(DoctorProfile)
        self.education.setGeometry(QtCore.QRect(90, 360, 161, 41))
        self.education.setStyleSheet("background-color: rgb(216, 216, 216);\n"
"border-radius: 20px;\n"
"padding-left:10px;")
        self.education.setObjectName("education")
        self.label_9 = QtWidgets.QLabel(DoctorProfile)
        self.label_9.setGeometry(QtCore.QRect(30, 350, 51, 51))
        self.label_9.setText("")
        self.label_9.setPixmap(QtGui.QPixmap("frontend\\images/school_45px.png"))
        self.label_9.setObjectName("label_9")
        self.label_3 = QtWidgets.QLabel(DoctorProfile)
        self.label_3.setGeometry(QtCore.QRect(30, 140, 51, 51))
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap("frontend\\images/gmail_logo_45px.png"))
        self.label_3.setObjectName("label_3")
        self.label_5 = QtWidgets.QLabel(DoctorProfile)
        self.label_5.setGeometry(QtCore.QRect(30, 210, 51, 51))
        self.label_5.setText("")
        self.label_5.setPixmap(QtGui.QPixmap("frontend\\images/password_45px.png"))
        self.label_5.setObjectName("label_5")
        self.label_7 = QtWidgets.QLabel(DoctorProfile)
        self.label_7.setGeometry(QtCore.QRect(30, 440, 51, 51))
        self.label_7.setText("")
        self.label_7.setPixmap(QtGui.QPixmap("frontend\\images/address_45px.png"))
        self.label_7.setObjectName("label_7")
        self.lastName = QtWidgets.QLineEdit(DoctorProfile)
        self.lastName.setGeometry(QtCore.QRect(290, 10, 171, 41))
        self.lastName.setStyleSheet("background-color: rgb(216, 216, 216);\n"
"border-radius: 20px;\n"
"padding-left:10px;")
        self.lastName.setObjectName("lastName")
        self.label_4 = QtWidgets.QLabel(DoctorProfile)
        self.label_4.setGeometry(QtCore.QRect(30, 70, 51, 51))
        self.label_4.setText("")
        self.label_4.setPixmap(QtGui.QPixmap("frontend\\images/add_phone_45px.png"))
        self.label_4.setObjectName("label_4")
        self.label_2 = QtWidgets.QLabel(DoctorProfile)
        self.label_2.setGeometry(QtCore.QRect(30, 0, 51, 51))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("frontend\\images/user_45px.png"))
        self.label_2.setObjectName("label_2")
        self.email = QtWidgets.QLineEdit(DoctorProfile)
        self.email.setGeometry(QtCore.QRect(90, 150, 371, 41))
        self.email.setStyleSheet("background-color: rgb(216, 216, 216);\n"
"border-radius: 20px;\n"
"padding-left:10px;")
        self.email.setObjectName("email")
        self.specialization = QtWidgets.QLineEdit(DoctorProfile)
        self.specialization.setGeometry(QtCore.QRect(270, 360, 181, 41))
        self.specialization.setStyleSheet("background-color: rgb(216, 216, 216);\n"
"border-radius: 20px;\n"
"padding-left:10px;")
        self.specialization.setObjectName("specialization")
        self.password = QtWidgets.QLineEdit(DoctorProfile)
        self.password.setGeometry(QtCore.QRect(90, 220, 271, 41))
        self.password.setStyleSheet("background-color: rgb(216, 216, 216);\n"
"border-radius: 20px;\n"
"padding-left:10px;")
        self.password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.password.setObjectName("password")
        self.cnfrmPassword = QtWidgets.QLineEdit(DoctorProfile)
        self.cnfrmPassword.setGeometry(QtCore.QRect(90, 290, 271, 41))
        self.cnfrmPassword.setStyleSheet("background-color: rgb(216, 216, 216);\n"
"border-radius: 20px;\n"
"padding-left:10px;")
        self.cnfrmPassword.setEchoMode(QtWidgets.QLineEdit.Password)
        self.cnfrmPassword.setObjectName("cnfrmPassword")
        self.registerButton = QtWidgets.QPushButton(DoctorProfile)
        self.registerButton.setGeometry(QtCore.QRect(100, 540, 161, 51))
        self.registerButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.registerButton.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 0, 127);\n"
"border-radius:5px;\n"
"font: 16pt \"Segoe UI\";")
        self.registerButton.setObjectName("registerButton")
        self.firstname = QtWidgets.QLineEdit(DoctorProfile)
        self.firstname.setGeometry(QtCore.QRect(90, 10, 171, 41))
        self.firstname.setStyleSheet("background-color: rgb(216, 216, 216);\n"
"border-radius: 20px;\n"
"padding-left:10px;")
        self.firstname.setObjectName("firstname")
        self.address = QtWidgets.QLineEdit(DoctorProfile)
        self.address.setGeometry(QtCore.QRect(90, 420, 391, 81))
        self.address.setStyleSheet("background-color: rgb(216, 216, 216);\n"
"border-radius: 25px;")
        self.address.setObjectName("address")
        self.mobile = QtWidgets.QLineEdit(DoctorProfile)
        self.mobile.setGeometry(QtCore.QRect(90, 80, 261, 41))
        self.mobile.setStyleSheet("background-color: rgb(216, 216, 216);\n"
"border-radius: 20px;\n"
"padding-left:10px;")
        self.mobile.setObjectName("mobile")
        self.label_6 = QtWidgets.QLabel(DoctorProfile)
        self.label_6.setGeometry(QtCore.QRect(30, 280, 51, 51))
        self.label_6.setText("")
        self.label_6.setPixmap(QtGui.QPixmap("frontend\\images/password_reset_45px.png"))
        self.label_6.setObjectName("label_6")
        self.registerButton_2 = QtWidgets.QPushButton(DoctorProfile)
        self.registerButton_2.setGeometry(QtCore.QRect(310, 540, 161, 51))
        self.registerButton_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.registerButton_2.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 0, 127);\n"
"border-radius:5px;\n"
"font: 16pt \"Segoe UI\";")
        self.registerButton_2.setObjectName("registerButton_2")

        self.retranslateUi(DoctorProfile)
        QtCore.QMetaObject.connectSlotsByName(DoctorProfile)

    def retranslateUi(self, DoctorProfile):
        _translate = QtCore.QCoreApplication.translate
        DoctorProfile.setWindowTitle(_translate("DoctorProfile", "Form"))
        self.education.setPlaceholderText(_translate("DoctorProfile", "Education"))
        self.lastName.setPlaceholderText(_translate("DoctorProfile", "Enter Your Last Name"))
        self.email.setPlaceholderText(_translate("DoctorProfile", "Enter Your mail"))
        self.specialization.setPlaceholderText(_translate("DoctorProfile", "Specialization"))
        self.password.setPlaceholderText(_translate("DoctorProfile", "Enter your password"))
        self.cnfrmPassword.setPlaceholderText(_translate("DoctorProfile", "Confirm password"))
        self.registerButton.setText(_translate("DoctorProfile", "Change"))
        self.firstname.setPlaceholderText(_translate("DoctorProfile", "Enter Your First Name"))
        self.address.setPlaceholderText(_translate("DoctorProfile", "Enter Your Address"))
        self.mobile.setPlaceholderText(_translate("DoctorProfile", "Enter Your mobile"))
        self.registerButton_2.setText(_translate("DoctorProfile", "Apply"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    DoctorProfile = QtWidgets.QWidget()
    ui = Ui_DoctorProfile()
    ui.setupUi(DoctorProfile)
    DoctorProfile.show()
    sys.exit(app.exec_())
