# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'frontend/doctordashboard.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DoctorDashboard(object):
    def setupUi(self, DoctorDashboard):
        DoctorDashboard.setObjectName("DoctorDashboard")
        DoctorDashboard.resize(1229, 657)
        DoctorDashboard.setStyleSheet("background-color:rgb(255,255,255);")
        self.statusbar = QtWidgets.QStatusBar(DoctorDashboard)
        self.statusbar.setGeometry(QtCore.QRect(0, 0, 3, 25))
        self.statusbar.setObjectName("statusbar")
        self.widget = QtWidgets.QWidget(DoctorDashboard)
        self.widget.setGeometry(QtCore.QRect(-10, -10, 291, 671))
        self.widget.setStyleSheet("background-color: rgb(0, 0, 127);")
        self.widget.setObjectName("widget")
        self.profileButton = QtWidgets.QPushButton(self.widget)
        self.profileButton.setGeometry(QtCore.QRect(50, 100, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.profileButton.setFont(font)
        self.profileButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.profileButton.setStyleSheet("QPushButton#profileButton{\n"
"    background-color:rgb(0,0,127);\n"
"    border-radius:5px;\n"
"    border-color:rgb(0,0,127);\n"
"    color:rgb(255,255,255)\n"
"}\n"
"\n"
"QPushButton#profileButton:hover{\n"
"    background-color:rgb(255,255,255);\n"
"    color:rgb(0,0,127)\n"
"}")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("frontend\\images/user_secured_45px.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.profileButton.setIcon(icon)
        self.profileButton.setIconSize(QtCore.QSize(30, 30))
        self.profileButton.setObjectName("profileButton")
        self.appointmentButton = QtWidgets.QPushButton(self.widget)
        self.appointmentButton.setGeometry(QtCore.QRect(50, 160, 201, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.appointmentButton.setFont(font)
        self.appointmentButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.appointmentButton.setStyleSheet("QPushButton#appointmentButton{\n"
"    background-color:rgb(0,0,127);\n"
"    border-radius:5px;\n"
"    border-color:rgb(0,0,127);\n"
"    color:rgb(255,255,255)\n"
"}\n"
"\n"
"QPushButton#appointmentButton:hover{\n"
"    background-color:rgb(255,255,255);\n"
"    color:rgb(0,0,127)\n"
"}")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("frontend\\images/schedule_45px.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.appointmentButton.setIcon(icon1)
        self.appointmentButton.setIconSize(QtCore.QSize(30, 30))
        self.appointmentButton.setObjectName("appointmentButton")
        self.patientButton = QtWidgets.QPushButton(self.widget)
        self.patientButton.setGeometry(QtCore.QRect(50, 220, 121, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.patientButton.setFont(font)
        self.patientButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.patientButton.setStyleSheet("QPushButton#patientButton{\n"
"    background-color:rgb(0,0,127);\n"
"    border-radius:5px;\n"
"    border-color:rgb(0,0,127);\n"
"    color:rgb(255,255,255)\n"
"}\n"
"\n"
"QPushButton#patientButton:hover{\n"
"    background-color:rgb(255,255,255);\n"
"    color:rgb(0,0,127)\n"
"}")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("frontend\\images/ecg_45px.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.patientButton.setIcon(icon2)
        self.patientButton.setIconSize(QtCore.QSize(30, 30))
        self.patientButton.setObjectName("patientButton")
        self.logoutButton = QtWidgets.QPushButton(self.widget)
        self.logoutButton.setGeometry(QtCore.QRect(50, 280, 121, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.logoutButton.setFont(font)
        self.logoutButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.logoutButton.setStyleSheet("QPushButton#logoutButton{\n"
"    background-color:rgb(0,0,127);\n"
"    border-radius:5px;\n"
"    border-color:rgb(0,0,127);\n"
"    color:rgb(255,255,255)\n"
"}\n"
"\n"
"QPushButton#logoutButton:hover{\n"
"    background-color:rgb(255,255,255);\n"
"    color:rgb(0,0,127)\n"
"}")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("frontend\\images/Logout_45px.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.logoutButton.setIcon(icon3)
        self.logoutButton.setIconSize(QtCore.QSize(30, 30))
        self.logoutButton.setObjectName("logoutButton")
        self.mainContainer = QtWidgets.QWidget(DoctorDashboard)
        self.mainContainer.setGeometry(QtCore.QRect(280, 0, 961, 661))
        self.mainContainer.setObjectName("mainContainer")

        self.retranslateUi(DoctorDashboard)
        QtCore.QMetaObject.connectSlotsByName(DoctorDashboard)

    def retranslateUi(self, DoctorDashboard):
        _translate = QtCore.QCoreApplication.translate
        DoctorDashboard.setWindowTitle(_translate("DoctorDashboard", "MainWindow"))
        self.profileButton.setText(_translate("DoctorDashboard", "Profile"))
        self.appointmentButton.setText(_translate("DoctorDashboard", "Appointment"))
        self.patientButton.setText(_translate("DoctorDashboard", "Patient"))
        self.logoutButton.setText(_translate("DoctorDashboard", "Logout"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    DoctorDashboard = QtWidgets.QWidget()
    ui = Ui_DoctorDashboard()
    ui.setupUi(DoctorDashboard)
    DoctorDashboard.show()
    sys.exit(app.exec_())
