# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'frontend/trailregister.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_RegisterWindow(object):
    def setupUi(self, RegisterWindow):
        RegisterWindow.setObjectName("RegisterWindow")
        RegisterWindow.resize(967, 740)
        RegisterWindow.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.centralwidget = QtWidgets.QWidget(RegisterWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(0, 0, 481, 681))
        self.widget.setObjectName("widget")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setGeometry(QtCore.QRect(0, 80, 461, 551))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("frontend\\images/real-doctor.jpg"))
        self.label.setObjectName("label")
        self.firstname = QtWidgets.QLineEdit(self.centralwidget)
        self.firstname.setGeometry(QtCore.QRect(560, 70, 171, 51))
        self.firstname.setStyleSheet("background-color: rgb(216, 216, 216);\n"
"border-radius: 25px;")
        self.firstname.setObjectName("firstname")
        self.mobile = QtWidgets.QLineEdit(self.centralwidget)
        self.mobile.setGeometry(QtCore.QRect(560, 140, 261, 51))
        self.mobile.setStyleSheet("background-color: rgb(216, 216, 216);\n"
"border-radius: 25px;")
        self.mobile.setObjectName("mobile")
        self.email = QtWidgets.QLineEdit(self.centralwidget)
        self.email.setGeometry(QtCore.QRect(560, 210, 371, 51))
        self.email.setStyleSheet("background-color: rgb(216, 216, 216);\n"
"border-radius: 25px;")
        self.email.setObjectName("email")
        self.password = QtWidgets.QLineEdit(self.centralwidget)
        self.password.setGeometry(QtCore.QRect(560, 280, 271, 51))
        self.password.setStyleSheet("background-color: rgb(216, 216, 216);\n"
"border-radius: 25px;")
        self.password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.password.setObjectName("password")
        self.lineEdit_6 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_6.setGeometry(QtCore.QRect(760, 70, 171, 51))
        self.lineEdit_6.setStyleSheet("background-color: rgb(216, 216, 216);\n"
"border-radius: 25px;")
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.cnfrmPassword = QtWidgets.QLineEdit(self.centralwidget)
        self.cnfrmPassword.setGeometry(QtCore.QRect(560, 350, 271, 51))
        self.cnfrmPassword.setStyleSheet("background-color: rgb(216, 216, 216);\n"
"border-radius: 25px;")
        self.cnfrmPassword.setEchoMode(QtWidgets.QLineEdit.Password)
        self.cnfrmPassword.setObjectName("cnfrmPassword")
        self.education = QtWidgets.QLineEdit(self.centralwidget)
        self.education.setGeometry(QtCore.QRect(560, 420, 161, 51))
        self.education.setStyleSheet("background-color: rgb(216, 216, 216);\n"
"border-radius: 25px;")
        self.education.setObjectName("education")
        self.specialization = QtWidgets.QLineEdit(self.centralwidget)
        self.specialization.setGeometry(QtCore.QRect(740, 420, 181, 51))
        self.specialization.setStyleSheet("background-color: rgb(216, 216, 216);\n"
"border-radius: 25px;")
        self.specialization.setObjectName("specialization")
        self.address = QtWidgets.QLineEdit(self.centralwidget)
        self.address.setGeometry(QtCore.QRect(560, 490, 391, 81))
        self.address.setStyleSheet("background-color: rgb(216, 216, 216);\n"
"border-radius: 25px;")
        self.address.setObjectName("address")
        self.registerButton = QtWidgets.QPushButton(self.centralwidget)
        self.registerButton.setGeometry(QtCore.QRect(650, 610, 161, 51))
        self.registerButton.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 0, 127);\n"
"border-radius:5px;\n"
"font: 16pt \"Segoe UI\";")
        self.registerButton.setObjectName("registerButton")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(500, 70, 51, 51))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("frontend\\images/user_45px.png"))
        self.label_2.setObjectName("label_2")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(500, 140, 51, 51))
        self.label_4.setText("")
        self.label_4.setPixmap(QtGui.QPixmap("frontend\\images/add_phone_45px.png"))
        self.label_4.setObjectName("label_4")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(500, 210, 51, 51))
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap("frontend\\images/gmail_logo_45px.png"))
        self.label_3.setObjectName("label_3")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(500, 280, 51, 51))
        self.label_5.setText("")
        self.label_5.setPixmap(QtGui.QPixmap("frontend\\images/password_45px.png"))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(500, 350, 51, 51))
        self.label_6.setText("")
        self.label_6.setPixmap(QtGui.QPixmap("frontend\\images/password_reset_45px.png"))
        self.label_6.setObjectName("label_6")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(500, 420, 51, 51))
        self.label_9.setText("")
        self.label_9.setPixmap(QtGui.QPixmap("frontend\\images/school_45px.png"))
        self.label_9.setObjectName("label_9")
        RegisterWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(RegisterWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 967, 26))
        self.menubar.setObjectName("menubar")
        RegisterWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(RegisterWindow)
        self.statusbar.setObjectName("statusbar")
        RegisterWindow.setStatusBar(self.statusbar)

        self.retranslateUi(RegisterWindow)
        QtCore.QMetaObject.connectSlotsByName(RegisterWindow)

    def retranslateUi(self, RegisterWindow):
        _translate = QtCore.QCoreApplication.translate
        RegisterWindow.setWindowTitle(_translate("RegisterWindow", "RegisterWindow"))
        self.firstname.setPlaceholderText(_translate("RegisterWindow", "Enter Your First Name"))
        self.mobile.setPlaceholderText(_translate("RegisterWindow", "Enter Your mobile"))
        self.email.setPlaceholderText(_translate("RegisterWindow", "Enter Your mail"))
        self.password.setPlaceholderText(_translate("RegisterWindow", "Enter your password"))
        self.lineEdit_6.setPlaceholderText(_translate("RegisterWindow", "Enter Your Last Name"))
        self.cnfrmPassword.setPlaceholderText(_translate("RegisterWindow", "Confirm password"))
        self.education.setPlaceholderText(_translate("RegisterWindow", "Education"))
        self.specialization.setPlaceholderText(_translate("RegisterWindow", "Specialization"))
        self.address.setPlaceholderText(_translate("RegisterWindow", "Enter Your Address"))
        self.registerButton.setText(_translate("RegisterWindow", "Register"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    RegisterWindow = QtWidgets.QMainWindow()
    ui = Ui_RegisterWindow()
    ui.setupUi(RegisterWindow)
    RegisterWindow.show()
    sys.exit(app.exec_())
