# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'frontend/dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(849, 468)
        Dialog.setStyleSheet("background-color: rgb(0, 170, 255);")
        self.changeWindow = QtWidgets.QPushButton(Dialog)
        self.changeWindow.setGeometry(QtCore.QRect(542, 308, 181, 51))
        self.changeWindow.setStyleSheet("background-color: rgb(255, 255, 127);\n"
"border-radius: 10px;")
        self.changeWindow.setObjectName("changeWindow")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.changeWindow.setText(_translate("Dialog", "ChangeWindow"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
