# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'frontend/individual_history.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_IndividualHistory(object):
    def setupUi(self, IndividualHistory):
        IndividualHistory.setObjectName("IndividualHistory")
        IndividualHistory.resize(1181, 51)
        IndividualHistory.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.historyPatientName = QtWidgets.QLabel(IndividualHistory)
        self.historyPatientName.setGeometry(QtCore.QRect(20, 10, 231, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.historyPatientName.setFont(font)
        self.historyPatientName.setObjectName("historyPatientName")
        self.historyPatientProblem = QtWidgets.QLabel(IndividualHistory)
        self.historyPatientProblem.setGeometry(QtCore.QRect(280, 10, 441, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.historyPatientProblem.setFont(font)
        self.historyPatientProblem.setObjectName("historyPatientProblem")
        self.historyPatientAppoint = QtWidgets.QLabel(IndividualHistory)
        self.historyPatientAppoint.setGeometry(QtCore.QRect(750, 10, 171, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.historyPatientAppoint.setFont(font)
        self.historyPatientAppoint.setObjectName("historyPatientAppoint")
        self.historyPatientStatus = QtWidgets.QLabel(IndividualHistory)
        self.historyPatientStatus.setGeometry(QtCore.QRect(980, 10, 171, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.historyPatientStatus.setFont(font)
        self.historyPatientStatus.setObjectName("historyPatientStatus")

        self.retranslateUi(IndividualHistory)
        QtCore.QMetaObject.connectSlotsByName(IndividualHistory)

    def retranslateUi(self, IndividualHistory):
        _translate = QtCore.QCoreApplication.translate
        IndividualHistory.setWindowTitle(_translate("IndividualHistory", "Form"))
        self.historyPatientName.setText(_translate("IndividualHistory", "Patient Name"))
        self.historyPatientProblem.setText(_translate("IndividualHistory", "Problem"))
        self.historyPatientAppoint.setText(_translate("IndividualHistory", "Appointment Date"))
        self.historyPatientStatus.setText(_translate("IndividualHistory", "Status"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    IndividualHistory = QtWidgets.QWidget()
    ui = Ui_IndividualHistory()
    ui.setupUi(IndividualHistory)
    IndividualHistory.show()
    sys.exit(app.exec_())
