# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'frontend/login.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_LoginWindow(object):
    def setupUi(self, LoginWindow):
        LoginWindow.setObjectName("LoginWindow")
        LoginWindow.resize(656, 590)
        LoginWindow.setStyleSheet("background-color:rgb(255,255,255);\n"
"border radius:30px;")
        self.centralwidget = QtWidgets.QWidget(LoginWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.usrname = QtWidgets.QLineEdit(self.centralwidget)
        self.usrname.setGeometry(QtCore.QRect(80, 250, 501, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.usrname.setFont(font)
        self.usrname.setStyleSheet("background-color:rgb(216,216,216);\n"
"border-radius:20px;\n"
"padding-left:10px;\n"
"padding-bottom:3px")
        self.usrname.setObjectName("usrname")
        self.password = QtWidgets.QLineEdit(self.centralwidget)
        self.password.setGeometry(QtCore.QRect(80, 310, 501, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.password.setFont(font)
        self.password.setStyleSheet("background-color:rgb(216,216,216);\n"
"border-radius:20px;\n"
"padding-left:10px;\n"
"padding-bottom:3px")
        self.password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.password.setObjectName("password")
        self.loginButton = QtWidgets.QPushButton(self.centralwidget)
        self.loginButton.setGeometry(QtCore.QRect(250, 380, 161, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        self.loginButton.setFont(font)
        self.loginButton.setStyleSheet("background-color:rgb(0,0,127);\n"
"color:rgb(255,255,255);\n"
"border-radius:20px;\n"
"\n"
"\n"
"\n"
"")
        self.loginButton.setObjectName("loginButton")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(150, 500, 201, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color:rgb(0,0,127);")
        self.label_2.setObjectName("label_2")
        self.registerButton = QtWidgets.QPushButton(self.centralwidget)
        self.registerButton.setGeometry(QtCore.QRect(380, 490, 121, 29))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        self.registerButton.setFont(font)
        self.registerButton.setStyleSheet("QPushButton#registerButton{\n"
"background-color:rgb(0,0,127);\n"
"color:rgb(255,255,255);\n"
"border-radius:5px;\n"
"}\n"
"\n"
"QPushButton#registerButton:pressed{\n"
"background-color:rgb(0,0,120);\n"
"}\n"
"\n"
"QPushButton#registerButton:hover{\n"
"background-color:rgb(0,0,120);\n"
"}\n"
"")
        self.registerButton.setObjectName("registerButton")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(240, 40, 161, 161))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("frontend\\images/medical-logo.jpg"))
        self.label.setObjectName("label")
        LoginWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(LoginWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 656, 26))
        self.menubar.setObjectName("menubar")
        self.menulogin = QtWidgets.QMenu(self.menubar)
        self.menulogin.setObjectName("menulogin")
        LoginWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(LoginWindow)
        self.statusbar.setObjectName("statusbar")
        LoginWindow.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menulogin.menuAction())

        self.retranslateUi(LoginWindow)
        QtCore.QMetaObject.connectSlotsByName(LoginWindow)

    def retranslateUi(self, LoginWindow):
        _translate = QtCore.QCoreApplication.translate
        LoginWindow.setWindowTitle(_translate("LoginWindow", "LoginWindow"))
        self.usrname.setPlaceholderText(_translate("LoginWindow", "Enter the username"))
        self.password.setPlaceholderText(_translate("LoginWindow", "Enter the password"))
        self.loginButton.setText(_translate("LoginWindow", "L o g i n"))
        self.label_2.setText(_translate("LoginWindow", "Don\'t have an account?"))
        self.registerButton.setText(_translate("LoginWindow", "R e g i s t e r"))
        self.menulogin.setTitle(_translate("LoginWindow", "login"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    LoginWindow = QtWidgets.QMainWindow()
    ui = Ui_LoginWindow()
    ui.setupUi(LoginWindow)
    LoginWindow.show()
    sys.exit(app.exec_())
