# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\frontend\patienthistory.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_PatientHistory(object):
    def setupUi(self, PatientHistory):
        PatientHistory.setObjectName("PatientHistory")
        PatientHistory.resize(788, 499)
        PatientHistory.setStyleSheet("background-color:rgb(255,255,255);\n"
"border-radius:12px;")
        self.widget_2 = QtWidgets.QWidget(PatientHistory)
        self.widget_2.setGeometry(QtCore.QRect(30, 30, 721, 111))
        self.widget_2.setStyleSheet("background-color:rgb(199,230,255);\n"
"border-radius:12px;")
        self.widget_2.setObjectName("widget_2")
        self.label = QtWidgets.QLabel(self.widget_2)
        self.label.setGeometry(QtCore.QRect(20, 20, 361, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.widget_2)
        self.label_2.setGeometry(QtCore.QRect(40, 70, 161, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.widget_2)
        self.label_3.setGeometry(QtCore.QRect(310, 70, 111, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.widget_2)
        self.label_4.setGeometry(QtCore.QRect(570, 70, 63, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.historyTable = QtWidgets.QTableWidget(PatientHistory)
        self.historyTable.setGeometry(QtCore.QRect(30, 170, 731, 291))
        self.historyTable.setStyleSheet("background-color:rgb(199,230,255);\n"
"border-radius:12px;")
        self.historyTable.setObjectName("historyTable")
        self.historyTable.setColumnCount(0)
        self.historyTable.setRowCount(0)

        self.retranslateUi(PatientHistory)
        QtCore.QMetaObject.connectSlotsByName(PatientHistory)

    def retranslateUi(self, PatientHistory):
        _translate = QtCore.QCoreApplication.translate
        PatientHistory.setWindowTitle(_translate("PatientHistory", "Form"))
        self.label.setText(_translate("PatientHistory", "Here\'s Your Appointment  History!"))
        self.label_2.setText(_translate("PatientHistory", "Consulted Doctor"))
        self.label_3.setText(_translate("PatientHistory", "Health Issue"))
        self.label_4.setText(_translate("PatientHistory", "Date"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    PatientHistory = QtWidgets.QWidget()
    ui = Ui_PatientHistory()
    ui.setupUi(PatientHistory)
    PatientHistory.show()
    sys.exit(app.exec_())
