# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\frontend\patientappointment.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_PatientAppointment(object):
    def setupUi(self, PatientAppointment):
        PatientAppointment.setObjectName("PatientAppointment")
        PatientAppointment.resize(646, 667)
        PatientAppointment.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius: 10px;")
        self.widget = QtWidgets.QWidget(PatientAppointment)
        self.widget.setGeometry(QtCore.QRect(40, 50, 561, 561))
        self.widget.setStyleSheet("background-color:rgb(199,230,255);\n"
"border-radius:12px;")
        self.widget.setObjectName("widget")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setGeometry(QtCore.QRect(20, 30, 271, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setItalic(True)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setGeometry(QtCore.QRect(20, 90, 231, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.healthIssue = QtWidgets.QLineEdit(self.widget)
        self.healthIssue.setGeometry(QtCore.QRect(20, 160, 411, 51))
        self.healthIssue.setStyleSheet("background-color: rgb(230, 230, 230);\n"
"border-radius:15px;\n"
"")
        self.healthIssue.setObjectName("healthIssue")
        self.label_3 = QtWidgets.QLabel(self.widget)
        self.label_3.setGeometry(QtCore.QRect(30, 130, 111, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_2.setGeometry(QtCore.QRect(130, 290, 113, 26))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.label_4 = QtWidgets.QLabel(self.widget)
        self.label_4.setGeometry(QtCore.QRect(30, 230, 231, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.pastHistory = QtWidgets.QLineEdit(self.widget)
        self.pastHistory.setGeometry(QtCore.QRect(20, 260, 411, 51))
        self.pastHistory.setStyleSheet("background-color: rgb(230, 230, 230);\n"
"border-radius:15px;\n"
"")
        self.pastHistory.setObjectName("pastHistory")
        self.label_5 = QtWidgets.QLabel(self.widget)
        self.label_5.setGeometry(QtCore.QRect(30, 330, 231, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.requestButton = QtWidgets.QPushButton(self.widget)
        self.requestButton.setGeometry(QtCore.QRect(180, 460, 171, 51))
        self.requestButton.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 0, 127);\n"
"border-radius:5px;\n"
"font: 16pt \"Segoe UI\";")
        self.requestButton.setObjectName("requestButton")
        self.prefferedDatetTime = QtWidgets.QDateTimeEdit(self.widget)
        self.prefferedDatetTime.setGeometry(QtCore.QRect(30, 370, 194, 26))
        self.prefferedDatetTime.setMinimumDate(QtCore.QDate(2022, 4, 7))
        self.prefferedDatetTime.setCalendarPopup(True)
        self.prefferedDatetTime.setObjectName("prefferedDatetTime")

        self.retranslateUi(PatientAppointment)
        QtCore.QMetaObject.connectSlotsByName(PatientAppointment)

    def retranslateUi(self, PatientAppointment):
        _translate = QtCore.QCoreApplication.translate
        PatientAppointment.setWindowTitle(_translate("PatientAppointment", "Form"))
        self.label.setText(_translate("PatientAppointment", "Book Appointment"))
        self.label_2.setText(_translate("PatientAppointment", "Fill the Details below:"))
        self.label_3.setText(_translate("PatientAppointment", "Health Issue"))
        self.label_4.setText(_translate("PatientAppointment", "Past medical history (If any)"))
        self.label_5.setText(_translate("PatientAppointment", "Preferred Time and time"))
        self.requestButton.setText(_translate("PatientAppointment", "Request "))
        self.prefferedDatetTime.setDisplayFormat(_translate("PatientAppointment", "dd/MM/yyyy h:mm AP"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    PatientAppointment = QtWidgets.QWidget()
    ui = Ui_PatientAppointment()
    ui.setupUi(PatientAppointment)
    PatientAppointment.show()
    sys.exit(app.exec_())
