# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'form.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_LoginWindow(object):
    def setupUi(self, LoginWindow):
        LoginWindow.setObjectName("LoginWindow")
        LoginWindow.resize(800, 600)
        LoginWindow.setStyleSheet("background-color: rgb(159, 205, 207);")
        self.clearButton = QtWidgets.QPushButton(LoginWindow)
        self.clearButton.setGeometry(QtCore.QRect(620, 120, 131, 41))
        self.clearButton.setStyleSheet("background-color: rgb(200, 46, 15);\n"
"font: 18pt \"Segoe UI\";")
        self.clearButton.setObjectName("clearButton")
        self.addButton = QtWidgets.QPushButton(LoginWindow)
        self.addButton.setGeometry(QtCore.QRect(620, 200, 131, 41))
        self.addButton.setStyleSheet("background-color: rgb(53, 200, 20);\n"
"font: 16pt \"Segoe UI\";")
        self.addButton.setObjectName("addButton")
        self.t1 = QtWidgets.QLineEdit(LoginWindow)
        self.t1.setGeometry(QtCore.QRect(250, 90, 181, 31))
        self.t1.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.t1.setObjectName("t1")
        self.label = QtWidgets.QLabel(LoginWindow)
        self.label.setGeometry(QtCore.QRect(200, 380, 381, 31))
        self.label.setStyleSheet("color: rgb(255, 255, 255);\n"
"border-color: rgb(255, 38, 0);\n"
"font: 16pt \"MS Gothic\";")
        self.label.setObjectName("label")

        self.retranslateUi(LoginWindow)
        QtCore.QMetaObject.connectSlotsByName(LoginWindow)

    def retranslateUi(self, LoginWindow):
        _translate = QtCore.QCoreApplication.translate
        LoginWindow.setWindowTitle(_translate("LoginWindow", "Widget"))
        self.clearButton.setText(_translate("LoginWindow", "Clear"))
        self.addButton.setText(_translate("LoginWindow", "Add"))
        self.label.setText(_translate("LoginWindow", "Hello World"))

class LoginForm(QtWidgets.QMainWindow,Ui_LoginWindow):
    def __init__(self) -> None:
        super().__init__()
        self.setupUi(self)   
        self.clearButton.clicked.connect(self.clickedMe)  
        self.addButton.clicked.connect(self.changeLabel)    
        print('Hello world I am imported from form')

    def clickedMe(self):
        print('Change Window')
        self.label.setText('')
        
    def changeLabel(self):
        self.label.setText(self.t1.text())
# if __name__ == "__main__":
#     import sys
#     app = QtWidgets.QApplication(sys.argv)
# #     LoginWindow = QtWidgets.QWidget()
#     ui = LoginForm()
# #     ui.setupUi(LoginWindow)
#     ui.show()
#     sys.exit(app.exec_())

