# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'form.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from widgettrail import Ui_widgetTrail


class Ui_LoginWindow(object):
    def setupUi(self, LoginWindow):
        LoginWindow.setObjectName("LoginWindow")
        LoginWindow.resize(800, 600)
        LoginWindow.setStyleSheet("background-color: rgb(159, 205, 207);")
        self.clearButton = QtWidgets.QPushButton(LoginWindow)
        self.clearButton.setGeometry(QtCore.QRect(620, 120, 131, 41))
        self.clearButton.setStyleSheet("background-color: rgb(200, 46, 15);\n"
"font: 18pt \"Segoe UI\";\n"
"border-radius: 20px;")
        self.clearButton.setObjectName("clearButton")
        self.addButton = QtWidgets.QPushButton(LoginWindow)
        self.addButton.setGeometry(QtCore.QRect(620, 200, 131, 41))
        self.addButton.setStyleSheet("background-color: rgb(53, 200, 20);\n"
"font: 16pt \"Segoe UI\";\n"
"border-radius: 30px;")
        self.addButton.setObjectName("addButton")
        self.t1 = QtWidgets.QLineEdit(LoginWindow)
        self.t1.setGeometry(QtCore.QRect(250, 90, 181, 31))
        self.t1.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.t1.setObjectName("t1")
        self.container = QtWidgets.QLabel(LoginWindow)
        self.container.setGeometry(QtCore.QRect(110, 190, 461, 311))
        self.container.setText("")
        self.container.setObjectName("container")

        self.retranslateUi(LoginWindow)
        QtCore.QMetaObject.connectSlotsByName(LoginWindow)

    def retranslateUi(self, LoginWindow):
        _translate = QtCore.QCoreApplication.translate
        LoginWindow.setWindowTitle(_translate("LoginWindow", "Widget"))
        self.clearButton.setText(_translate("LoginWindow", "Clear"))
        self.addButton.setText(_translate("LoginWindow", "Add"))

class LoginForm(QtWidgets.QMainWindow,Ui_LoginWindow):
    def __init__(self) -> None:
        super().__init__()
        self.setupUi(self)
        self.addButton.clicked.connect(self.changeWidget)
        self.clearButton.clicked.connect(self.removeWidget)

    def changeWidget(self):
        widget_ui = Ui_widgetTrail()
        # widget_ui.trailButton.clicked.connect(self.widgetButtonTrail)
        widget_ui.setupUi(self.container)
        self.container.show()

    

    def removeWidget(self):
        self.container.hide()

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    LoginWindow = LoginForm()
    LoginWindow.show()
    sys.exit(app.exec_())

