# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'tabwidget.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_TabWidget(object):
    def setupUi(self, TabWidget):
        TabWidget.setObjectName("TabWidget")
        TabWidget.resize(1062, 577)
        TabWidget.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.home = QtWidgets.QWidget()
        self.home.setObjectName("home")
        self.homeButton = QtWidgets.QPushButton(self.home)
        self.homeButton.setGeometry(QtCore.QRect(360, 240, 251, 91))
        self.homeButton.setStyleSheet("background-color: rgb(91, 255, 82);")
        self.homeButton.setObjectName("homeButton")
        TabWidget.addTab(self.home, "")
        self.appointment = QtWidgets.QWidget()
        self.appointment.setObjectName("appointment")
        self.appointmentButton = QtWidgets.QPushButton(self.appointment)
        self.appointmentButton.setGeometry(QtCore.QRect(410, 230, 251, 91))
        self.appointmentButton.setStyleSheet("background-color: rgb(91, 255, 82);")
        self.appointmentButton.setObjectName("appointmentButton")
        TabWidget.addTab(self.appointment, "")
        self.history = QtWidgets.QWidget()
        self.history.setObjectName("history")
        self.historyButton = QtWidgets.QPushButton(self.history)
        self.historyButton.setGeometry(QtCore.QRect(410, 240, 251, 91))
        self.historyButton.setStyleSheet("background-color: rgb(91, 255, 82);")
        self.historyButton.setObjectName("historyButton")
        TabWidget.addTab(self.history, "")

        self.retranslateUi(TabWidget)
        TabWidget.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(TabWidget)

    def retranslateUi(self, TabWidget):
        _translate = QtCore.QCoreApplication.translate
        TabWidget.setWindowTitle(_translate("TabWidget", "TabWidget"))
        self.homeButton.setText(_translate("TabWidget", "Home"))
        TabWidget.setTabText(TabWidget.indexOf(self.home), _translate("TabWidget", "Home"))
        self.appointmentButton.setText(_translate("TabWidget", "Appointment"))
        TabWidget.setTabText(TabWidget.indexOf(self.appointment), _translate("TabWidget", "Appointment"))
        self.historyButton.setText(_translate("TabWidget", "History"))
        TabWidget.setTabText(TabWidget.indexOf(self.history), _translate("TabWidget", "History"))

class TabTrail(QtWidgets.QTabWidget,Ui_TabWidget):
    def __init__(self) -> None:
        super().__init__()
        self.setupUi(self)
        self.setWindowIcon(QtGui.QIcon('frontend/images/medical-logo.jpg'))
        self.homeButton.clicked.connect(self.sethome)
        self.appointmentButton.clicked.connect(self.setappoint)
        self.historyButton.clicked.connect(self.sethistory)

    def sethistory(self):
        print('history is clicked')

    def setappoint(self):
        print('appointment is clicked')

    def sethome(self):
        print('home is clicked')

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    TabWidget = TabTrail()
    TabWidget.show()
    sys.exit(app.exec_())
