# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'frontend/widget-trail.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_widgetTrail(object):
    def setupUi(self, widgetTrail):
        widgetTrail.setObjectName("widgetTrail")
        widgetTrail.resize(289, 217)
        widgetTrail.setWindowTitle("")
        widgetTrail.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.trailButton = QtWidgets.QPushButton(widgetTrail)
        self.trailButton.setGeometry(QtCore.QRect(80, 80, 131, 51))
        self.trailButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.trailButton.setStyleSheet("color: rgb(85, 170, 0);\n"
"background-color: rgb(255, 170, 0);")
        self.trailButton.setObjectName("trailButton")

        self.retranslateUi(widgetTrail)
        QtCore.QMetaObject.connectSlotsByName(widgetTrail)

    def retranslateUi(self, widgetTrail):
        _translate = QtCore.QCoreApplication.translate
        self.trailButton.setText(_translate("widgetTrail", "Trail action"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    widgetTrail = QtWidgets.QWidget()
    ui = Ui_widgetTrail()
    ui.setupUi(widgetTrail)
    widgetTrail.show()
    sys.exit(app.exec_())
